language: java

sudo: false

service:
  - docker

notifications:
  slack:
    iosr-workgroup:8wdjZUlR1MD3XQN16znNltRq#miosr_crud

script:
  - if [ -n "$TRAVIS_TAG" ]
    then
      mvn clean package -Dmaven.test.skip=true;
      exit 0;
    fi

    mvn clean test;

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
      docker build -t "kroczi/miosr-crud:$TRAVIS_TAG" -f Dockerfile . ;
      docker login -u "$DOCKER_USERNAME_MK" -p "$DOCKER_PASSWORD_MK";
      docker push kroczi/miosr-crud;
    fi