steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package', '-Dmaven.test.skip=true']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME', '.']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME']